name = "AsymptoticGaussianQuadrature"
uuid = "29d1a447-ebbf-4572-97ac-317b19e47030"
authors = ["Daan Huybrechs <daan.huybrechs@kuleuven.be>"]
version = "0.1.0"

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
FastGaussQuadrature = "0.5"
Roots = "2.0"
SpecialFunctions = "2.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
